# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18Xi_KkLE95r8fIVQiljh_mQ66RCBHixt
"""

import gradio as gr

def reverse_text(text):
    return text[::-1]

iface = gr.Interface(fn=reverse_text, inputs="text", outputs="text", title="Text Reversal")
iface.launch()